---
title: "291 data cleaning"
author: "Yingqi Zheng"
date: "11/8/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(tidyverse)
require(dplyr)
require(magrittr)
library(readxl)
Agriculture<- read_excel("~/SDS291-Final-Project 2/Agriculture.xls")
Energy_Eff<- read_excel("~/SDS291-Final-Project 2/Energy_Eff.xls")
Energy_Import<- read_excel("~/SDS291-Final-Project 2/Energy_import.xls")
Income_Level <- read_excel("~/SDS291-Final-Project 2/Income Level.xls")
Industry <- read_excel("~/SDS291-Final-Project 2/Industry.xls")
Renewable_pcent <- read_excel("~/SDS291-Final-Project 2/Renewable_pcent.xls")
Service <- read_excel("~/SDS291-Final-Project 2/Service.xls")
GNI <- read_excel("~/SDS291-Final-Project 2/GNI.xls")
Emp_Pop <- read_excel("~/SDS291-Final-Project 2/emp_pop.xls")
education_index<- read_excel("~/SDS291-Final-Project 2/education_index.xlsx")
```

```{r}
Masterdata <- subset(Agriculture, select = c('Country Name', '2014'))
colnames(Masterdata)[colnames(Masterdata) == "2014"] <- "Agriculture"
Combine <- function(x,y) {data <- subset(x, select = c('Country Name', '2014'))
                         colnames(data)[colnames(data) == "2014"] <- y
                         Masterdata %>%
                         inner_join(data, by = 'Country Name')}
Masterdata <- Combine(Energy_Import, "Energy_Import")


```

```{r}
Masterdata <- Combine(Energy_Eff,"Energy_Eff")
Masterdata <- Combine(Service,"Service")
Masterdata <- Combine(Renewable_pcent,"Renewable")
Masterdata <- Combine(Industry,"Industry")
Masterdata <- Combine(Emp_Pop,"Emp_Pop")
Masterdata <- Combine(education_index,"education_index")
colnames(Income)[colnames(Income) == "TableName"] <- 'Country Name'
colnames(Income)[colnames(Income) == 'Income Level'] <- 'Income_Level'
Income <- subset(Income, select = c('Income_Level','Country Name'))
Masterdata <- Masterdata %>%
    inner_join(Income, by = 'Country Name')
Masterdata <- Combine(GNI,"GNI")
MasterdataNNA <- na.omit(Masterdata)
```

```{r message = FALSE}
library(writexl)
write_xlsx(MasterdataNNA, "~/SDS291-Final-Project 2/Masterdata 1212017.xls")
```


 
 c(Energy_Efficiency1,Energy_Import1, Services_value_added1,Renewable_1,Industry_value_added1,Income_Level1)

c("Energy_Efficiency","Energy_Import","Services_value_added", "Renewable","Industry_value_added","Income_Level")

Masterdata <- Combine(Energy_Import1, "Energy_Import")